import React from "react";

export const homeStyles: { [key: string]: React.CSSProperties } = {
  pageContainer: {
    backgroundColor: "#000",
    color: "#fff",
    minHeight: "100vh",
    overflowX: "hidden",
    width: "100%",
  },
  heroSplit: {
    minHeight: "100vh",
    display: "flex",
    width: "100%",
    backgroundAttachment: "fixed", // Note: Logic for mobile 'scroll' should stay in the component
    backgroundImage:
      'linear-gradient(to right, rgba(15,15,15,1) 35%, rgba(15,15,15,0.2) 100%), url("/assets/images/register-sky.jpg")',
    backgroundSize: "cover",
    boxSizing: "border-box",
  },
  heroLeft: {
    flex: 1.2,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    paddingLeft: "8%",
    zIndex: 2,
  },
  heroRight: {
    flex: 0.8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingRight: "8%",
    zIndex: 2,
  },
  dataContainer: {
    width: "100%",
    maxWidth: "450px",
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    border: "1px solid #1a1a1a",
    padding: "20px",
    backdropFilter: "blur(15px)",
  },
  dataHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "20px",
    borderBottom: "1px solid #1a1a1a",
    paddingBottom: "10px",
  },
  dataTitle: {
    fontSize: "0.6rem",
    letterSpacing: "2px",
    color: "#444",
    fontWeight: "bold",
  },
  liveIndicator: { display: "flex", alignItems: "center", gap: "8px" },
  pulseDot: {
    width: "6px",
    height: "6px",
    borderRadius: "50%",
    backgroundColor: "#d4ff00",
    boxShadow: "0 0 8px #d4ff00",
  },
  dataStatus: { fontSize: "0.55rem", color: "#d4ff00", letterSpacing: "1px" },
  chartBox: {
    height: "180px",
    width: "100%",
    marginBottom: "25px",
    position: "relative",
  },
  metricRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr 1.2fr",
    gap: "10px",
  },
  metricItem: { display: "flex", flexDirection: "column" },
  metricLabel: {
    fontSize: "0.5rem",
    color: "#666",
    letterSpacing: "1px",
    marginBottom: "5px",
  },
  metricValue: {
    fontFamily: "var(--font-bebas)",
    fontSize: "1.8rem",
    transition: "color 0.3s ease",
  },
  timestampValue: {
    fontFamily: "monospace",
    fontSize: "0.9rem",
    color: "#d4ff00",
    marginTop: "8px",
  },
  brandContent: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  topHeroLogo: {
    width: "100px",
    height: "100px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "40px",
    border: "2px solid #d4ff00",
    borderRadius: "50%",
    backgroundColor: "#fff",
    overflow: "hidden",
  },
  logoImageStyle: { width: "70%", height: "70%", objectFit: "contain" },
  heroTitleLeft: {
    fontFamily: "var(--font-bebas)",
    lineHeight: "0.85",
    margin: "0",
    color: "#fff",
    letterSpacing: "2px",
  },
  heroTagline: {
    fontFamily: "var(--font-bebas)",
    letterSpacing: "8px",
    margin: "10px 0 20px 0",
  },
  ctaBtn: {
    padding: "18px 50px",
    border: "2px solid #fff",
    background: "none",
    color: "#fff",
    cursor: "pointer",
    letterSpacing: "3px",
    fontWeight: "bold",
    fontSize: "0.8rem",
    transition: "0.3s",
  },
  pillarSection: { padding: "100px 8%" },
  sectionTitle: {
    fontFamily: "var(--font-bebas)",
    fontSize: "3rem",
    textTransform: "uppercase",
  },
  pillarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "30px",
  },
  pillarCard: {
    borderRadius: "12px",
    overflow: "hidden",
    backgroundColor: "#0a0a0a",
    border: "1px solid #1a1a1a",
    textDecoration: "none",
    color: "inherit",
  },
  pillarImageOverlay: {
    height: "250px",
    width: "100%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    transition: "all 0.4s ease-in-out",
    filter: "saturate(1.2) contrast(1.1)",
  },
  pillarContent: { padding: "20px" },
  cardNum: { color: "#d4ff00", fontSize: "0.8rem", marginBottom: "10px" },
  cardTitle: { fontFamily: "var(--font-bebas)", fontSize: "2.5rem", margin: 0 },
  archiveSection: { padding: "120px 8%" },
  archiveTitle: { fontFamily: "var(--font-bebas)", fontSize: "3rem" },
  articleGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "30px",
  },
  articleCard: {
    backgroundColor: "#0a0a0a",
    borderRadius: "12px",
    overflow: "hidden",
    border: "1px solid #1a1a1a",
    textDecoration: "none",
    color: "inherit",
  },
  articleImg: {
    width: "100%",
    height: "250px",
    objectFit: "cover",
    transition: "all 0.6s ease",
  },
  articleContent: { padding: "20px" },
  volTag: { color: "#d4ff00", fontSize: "0.7rem", letterSpacing: "2px" },
  articleTitle: {
    fontFamily: "var(--font-bebas)",
    fontSize: "2rem",
    margin: "10px 0",
  },
  lockedChartOverlay: {
    height: "100%",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(10, 10, 10, 0.5)",
    border: "1px dashed #333",
    color: "#444",
    fontFamily: "var(--font-bebas)",
    fontSize: "1.5rem",
    letterSpacing: "4px",
  },
};
// Add these to your existing homeStyles object in styles.ts
export const mobileStyles: { [key: string]: React.CSSProperties } = {
  mobileSection: {
    padding: "100px 20px",
    backgroundColor: "transparent",
    maxWidth: "1200px",
    margin: "0 auto",
  },
  headerStack: {
    textAlign: "center",
    marginBottom: "60px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  mobileTitle: {
    letterSpacing: "2px",
    fontWeight: "900",
    margin: "0 0 15px 0",
    textTransform: "uppercase",
    fontFamily: "var(--font-bebas)",
    fontSize: "3rem",
  },
  mobileDesc: {
    fontSize: "0.85rem",
    color: "#666",
    lineHeight: "1.8",
    maxWidth: "550px",
    letterSpacing: "1.5px",
    textTransform: "uppercase",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "30px",
    marginBottom: "100px",
    padding: "0 20px",
  },
  mobileCard: {
    aspectRatio: "9/16",
    backgroundColor: "#080808",
    borderRadius: "14px",
    border: "1px solid #1a1a1a",
    overflow: "hidden",
    position: "relative",
    transition: "all 0.5s cubic-bezier(0.2, 0.8, 0.2, 1)",
    cursor: "pointer",
    width: "100%",
    maxWidth: "320px",
    margin: "0 auto",
  },
  cardInternal: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  mockImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    filter: "brightness(0.8) contrast(1.1)",
    transition: "all 0.5s ease",
  },
  imgOverlay: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(to bottom, transparent 60%, rgba(0,0,0,0.9) 100%)",
    display: "flex",
    alignItems: "flex-end",
    padding: "20px",
    justifyContent: "center",
  },
  placeholderTag: {
    fontSize: "0.55rem",
    color: "#d4ff00",
    letterSpacing: "3px",
    zIndex: 2,
    fontFamily: "monospace",
    backgroundColor: "rgba(0,0,0,0.7)",
    padding: "4px 8px",
    borderRadius: "2px",
  },
  footerDownload: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    alignItems: "center",
    gap: "80px",
    opacity: 0.8,
  },
  inlineBadgeContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "15px",
  },
  badgeLabel: {
    fontSize: "0.6rem",
    letterSpacing: "4px",
    color: "#444",
  },
  badgeWrapperRow: {
    display: "flex",
    gap: "20px",
  },
  badgeImg: {
    height: "34px",
    cursor: "pointer",
    filter: "grayscale(1) brightness(0.6)",
    transition: "0.3s",
  },
  glowEffect: {
    position: "absolute",
    bottom: "-10%",
    width: "100%",
    height: "30%",
    backgroundColor: "#d4ff00",
    filter: "blur(45px)",
    transition: "opacity 0.4s ease",
    zIndex: 1,
  },
  sectionNum: {
    color: "#333",
    fontSize: "0.6rem",
    letterSpacing: "5px",
    display: "block",
    textAlign: "center",
    marginBottom: "8px",
  },
  pillarSection: { padding: "100px 8%" },
  sectionTitle: {
    fontFamily: "var(--font-bebas)",
    fontSize: "3rem",
    textTransform: "uppercase",
  },
  pillarGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "30px",
  },
  pillarCard: {
    borderRadius: "12px",
    overflow: "hidden",
    backgroundColor: "#0a0a0a",
    border: "1px solid #1a1a1a",
    textDecoration: "none",
    color: "inherit",
    display: "block",
  },
  pillarImageOverlay: {
    height: "250px",
    width: "100%",
    backgroundSize: "cover",
    backgroundPosition: "center",
    transition: "all 0.4s ease-in-out",
  },
  pillarContent: { padding: "20px" },
  cardNum: { color: "#d4ff00", fontSize: "0.8rem", marginBottom: "10px" },
  cardTitle: { fontFamily: "var(--font-bebas)", fontSize: "2.5rem", margin: 0 },

  archiveSection: { padding: "120px 8%" },
  articleGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "30px",
  },
  articleCard: {
    backgroundColor: "#0a0a0a",
    borderRadius: "12px",
    overflow: "hidden",
    border: "1px solid #1a1a1a",
    textDecoration: "none",
    color: "inherit",
    transition: "0.3s ease",
  },
  articleImg: {
    width: "100%",
    height: "250px",
    objectFit: "cover",
    transition: "all 0.6s ease",
    filter: "grayscale(0.5) brightness(0.8)",
  },
  articleContent: { padding: "20px" },
  volTag: { color: "#d4ff00", fontSize: "0.7rem", letterSpacing: "2px" },
  articleTitle: {
    fontFamily: "var(--font-bebas)",
    fontSize: "2rem",
    margin: "10px 0",
  },
};
